language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
   - pecl install imagick

install: composer install

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
